### ISSUE TITLE
Unknown property

### ISSUE THREAD

**Issue by dmulih** [limion/yii2-jquery-fileupload-widget#1]
Am getting this error in yii 2 what might be the issue?

error is "Setting unknown property: limion\jqueryfileupload\JQueryFileUpload::clientOptions"

**Comment by limion** [comment]
Hi, sorry for the late answer, I was on vocation.
Do you have yii2-jui package installed? Try to add this in you composer.json:
"yiisoft/yii2-jui": "*"
It seems like I forgot to include it to the dependence list.

**Comment by limion** [comment]
I've updated the dependencies. Just make: composer update.
