### ISSUE TITLE
view main.php - file-upload-progress not displaying

### ISSUE THREAD

**Issue by techie42** [limion/yii2-jquery-fileupload-widget#2]
Hi,
Around line 23 of main.php in the views folder, the fileupload-progress div has a class "fade".

There is a "fade" class in Twitter Bootstrap (v3), so the class should be "fade in" so that the fade actually works. I don't know if this issue arises elsewhere as I'm using the "basic" version.

The voted answer here ([http://stackoverflow.com/questions/18756981/twitter-bootstrap-3-tab-view-fade-does-not-work-properly](http://stackoverflow.com/questions/18756981/twitter-bootstrap-3-tab-view-fade-does-not-work-properly)) explains why.

Thanks for the widget ... works nicely :)

**Comment by limion** [comment]
Hi, I will look closely on Monday but for now you can use custom template. Just copy main.php and edit it as you need.
Thanks and you are welcome:)

**Comment by limion** [comment]
@techie42 I have removed class "fade" from basic version. Now global progress bar is always visible. Thank you for your attentiveness!
