### ISSUE TITLE
UI version does not return list of uploaded files

### ISSUE THREAD

**Issue by katag9k** [limion/yii2-jquery-fileupload-widget#3]
Form:

```
<?= JQueryFileUpload::widget( [
    'model'         => $model,
    'attribute'     => 'uploaded_photos',
    'url'           => [ 'media/image-upload', 'id' => $model->id ],
    'gallery'       => true,
    'formId'        => $form->id,
    'options'       => [
        'accept' => 'image/*'
    ],
    'clientOptions' => [
        'maxFileSize'     => 2000000,
        'dataType'        => 'json',
        'acceptFileTypes' => new yii\web\JsExpression( '/(\.|\/)(jpe?g|png)$/i' ),
        'autoUpload'      => true
    ],
] );
?>
```

In Controller post comes through empty:

```
$model = new Model();

if (Yii::$app->request->post()) {
    print_r(Yii::$app->request->post());
    Yii::$app->end();
}
```

In Model rules:

`[ [ 'uploaded_photos' ], 'safe' ]`

Am I supposed to manually append all the files to a hidden text field in `clientEvents`?

**Comment by limion** [comment]
@kategee, if you are uploading files with "multipart/form-data" form you need to look for Model['uploaded_photos'] in $_FILES global var. Uploaded file is not a POST parameter.
As upload handler you can use jquery-fileupload legacy php uploader: https://github.com/blueimp/jQuery-File-Upload/wiki#php
Or you can write your own using Yii2: http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html, 
but pay attention that jquery-fileupload javascript component waits for answer from the server in the format like legacy uploader returns.

```
{
   "files":[
      {
         "name":"8acbf304aff6e1863ebff5e9c795f8ef.jpg",
         "size":4182,
         "type":"image/jpeg",
         "url":"/upload/8acbf304aff6e1863ebff5e9c795f8ef.jpg",
         "thumbnailUrl":"/upload/thumbnail/8acbf304aff6e1863ebff5e9c795f8ef.jpg",
         "deleteUrl":"/upload/?param=files&_method=DELETE&files=8acbf304aff6e1863ebff5e9c795f8ef.jpg",
         "deleteType":"POST"
      }
   ]
}
```

**Comment by katag9k** [comment]
Sorry I think I didn't explain properly. The files upload fine, I have a bunch that get uploaded to the temp directory automatically. I'm having issues accessing all the data from the uploaded files in my controller. I'm assuming that the JSON output of the fileupload gets stored somewhere in a hidden field  in the form, that's why I'm looking for a POST and not FILES (as files are already uploaded). So where does the files json go? It seems to be returned but not stored anywhere in the form?

So when I submit the form that has a bunch of temp files uploaded, I need to process them and move them over to the appropriate folder etc in my controller:

```
$model = new UploadForm();

if (Yii::$app->request->isPost) {
    $files = UploadedFile::getInstance( $model, 'uploaded_photos' );
    print_r($files);
    print_r($_POST);
    Yii::$app->end();
}
```

Everything returns empty:

`[UploadForm] => Array ( [uploaded_photos] => ) )`

**Comment by limion** [comment]
JSON output you make by yourself based on uploaded files. You do it by your own upload handler. This widget provides smooth work with `bluimp-file-upload` in `Yii2`. There is no backend part.
