### ISSUE TITLE
Initialize with some images

### ISSUE THREAD

**Issue by elis88** [limion/yii2-jquery-fileupload-widget#5]
Is it possible, to initialize some images before user uploads?

**Comment by limion** [comment]
@elis88 What do you mean by 'initialize' ? 
For example here http://blueimp.github.io/jQuery-File-Upload/basic-plus.html it's possible to preview images before uploading.

**Comment by elis88** [comment]
@limion  thank you for your respond. 
My case is that I have a form, on submit it validates the fields, and if the form is not valid it returns me to form to see the errors.  In this case I'd like to see the images that I had uploaded before. I use Basic Plus UI.

**Comment by limion** [comment]
@elis88 If the form was submitted and validated on backend side you can save images in some temporary place (table/folder) and read them if the form is not valid. This widget doesn't provide backend part, you do it by yourselft. See https://github.com/limion/yii2-jquery-fileupload-widget/issues/3
