### ISSUE TITLE
problem when use on modal

### ISSUE THREAD

**Issue by by12** [limion/yii2-jquery-fileupload-widget#6]
Hello,
     Thanks for great contribution. I am using this since long. working perfectly. Now first time i used this widget on bootstrap modal. Still working but strange thing is that when i close the modal it destroy the mein page layout. and some css not exist anymore. But when i remove the widget from the modal then i dont have any issue.
Have any idea?
Thank you

**Comment by limion** [comment]
Hi, @by12 ,
could you please provide some basic code to reproduce the issue? Somewhere like https://jsfiddle.net/ ? It looks like not yii-related but js/frontend issue.

**Comment by by12** [comment]
hi,
    I recheck everything. I found that problem only appear when i render the view by using renderAjax in yii. and it always show following error in console.

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

May be problem because of  jquery.Ajax and Ajax call from yii.
But i don't know how i can solve this problem.

**Comment by by12** [comment]
hello,
    i solved the issue by prevent to re initialize the same Asset Bundles on view(render by renderAjax);
added following code to view or controller before render,

Yii::$app->assetManager->bundles = [
        'yii\bootstrap\BootstrapPluginAsset' => false,
        'yii\bootstrap\BootstrapAsset' => false,
        'yii\web\JqueryAsset' => false,
    ];

reference: https://github.com/yiisoft/yii2/issues/6838

thanks.
